### ISSUE TITLE
Not working in US

### ISSUE THREAD

**Issue by jeremyakers** [gboudreau/LEAF_Carwings_EasyAccess#1]
When I try to use in the US I get a message saying "We've moved" and it tries to redirect to the new Nissan website,

**Comment by gboudreau** [comment]
Carwings was deprecated in favour of NissanConnect a few days ago. I made the necessary changes for Canada, since this is where I live, but for the US, I couldn't test, as I don't have a username & password for a US LEAF.
If you want to share your username and password (I would recommend temporarily changing your password to do so), please [send them to me in private](https://www.pommepause.com/contact/) , and I'll see what I can do to fix this for the US too.

**Comment by jeremyakers** [comment]
Hi Guillaume,

Thanks for the prompt reply.  This is actually for my girlfriends car.  I
have a Nissan Connect login but you can't see the Nissan Connect EV tab on
the website when you use my login, so I'm having her change hers.

As soon as she gets it changed I'll contact you directly with the details.

Thanks again, we have very much enjoyed the one click shortcuts prior to
the Nissan website switching over.  I've been keeping an eye on your github
page for updates and when I saw there were updates a week ago for
NissanConnect EV in Canada I was hoping they worked in the US as well, but
obviously not. :)

-Jeremy

**Comment by jeremyakers** [comment]
Hi Guillaume,

I thought I'd let you know that I tried to access the website link you gave
me to contact you:  https://www.pommepause.com/contact/

But the "Submit" button doesn't display for me in Firefox.  I was able to
get it to work in Chrome though.  Just thought you'd like to know.

-Jeremy

**Comment by gboudreau** [comment]
There you go.
I only tested with the status function; I'll let you try the Start Charging & Climate Control functions.

**Comment by jeremyakers** [comment]
So I tested the climate control earlier today but didn't get a chance to test the charging until the car was home this afternoon.

However it now appears that everything (Climate, Ststus, Charging) all seem to fail with this error:

"Fan ON failed:
Gateway Timeout
The proxy server did not receive a timely response from the upstream server.

Reference #1.d8fd4317.1446238592.38fd744 "

But I think it's an issue on Nissan's side, it doesn't seem to work when I try directly on the nissanusa.com website either.

-Jeremy

**Comment by gboudreau** [comment]
That can also be an issue with your web host.
The NissanConnect website takes longer to return a reply, while Carwings was pretty fast. So when you try to do any of those commands, if it takes too long, your web host will give up, thinking the PHP script has hanged, while in fact it is still waiting for the NissanConnect website to return a response.
If possible, increase the read timeout delay on your web host.

**Comment by gboudreau** [comment]
Indeed, right now, the NissanConnect generates 504 Gateway time-out errors. They timeout after 2 minutes on their side, and earlier today, it often took almost 2 minutes for the requests to complete. I guess they reached the threshold sometimes today.

**Comment by jeremyakers** [comment]
So that did seem to be a temporary issue with the Nissan website.

Now that the website is working again, it does appear there is one minor issue with the EasyAccess code still:  When you choose "Start Charge", it seems to successfully send the start charge command, but it reports back that it failed:

"Charge Start failed: START"

Seems like a minor UI issue, because the car does start charging.

**Comment by gboudreau** [comment]
OK. This commit (above) should fix that.
