### ISSUE TITLE
Status not showing miles for COUNTRY_US

### ISSUE THREAD

**Issue by dlarue** [gboudreau/LEAF_Carwings_EasyAccess#4]
I'm seeing kilometers for my distances in the status message/dialog even though my config is setup with these:
               'country' => NissanConnect::COUNTRY_US,
                'tz' => 'America/Los_Angeles'

But the config->country test is not passing for 'US' on this line and is falling through to the else/km settings:
https://github.com/gboudreau/LEAF_Carwings_EasyAccess/blob/master/nissan-connect-php/NissanConnect.class.php#L227

**Comment by dlarue** [comment]
line 227 should be testing for NNA instead of US
as in:
} elseif ($this->config->country == 'NNA')

**Comment by gboudreau** [comment]
Thx. Fixed.
