### ISSUE TITLE
Problems with Connection

### ISSUE THREAD

**Issue by gerfur1** [gboudreau/LEAF_Carwings_EasyAccess#6]
Had Problems with the connection since 5 Days, before all worked ok. After Update to the new Version following Problem/Error:

An error occurred: Login failed, or failed to find car VIN, authToken or accountID in response of login request: {"errorMessage":"Authentication Failure","errorCode":910,"status":200}

Can you help me? Thanks.

**Comment by gboudreau** [comment]
What value do you use for the `$country` parameter?
I have this issue when I used `NCI` instead of `CA`.

**Comment by FirePT** [comment]
Hi, having the same problem in Europe... Tried different combinations of country and language but always :
`{
    "errorMessage": "Authentication Failure",
    "errorCode": 910
}`

**Comment by gboudreau** [comment]
In Europe, I don't know what the correct country codes are; they changed in Canada, so I guess they would have changed in Europe too.
You would need to use a proxy while using the app on your mobile device, to find the correct country to use.

**Comment by gerfur1** [comment]
If i use the old script with base url 
private $baseURL = 'https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/';
it works.

**Comment by gboudreau** [comment]
So it works with the old script, or doesn't?
I thought you had issues with the old script, like many other users, and upgraded to the latest version because of that (https://github.com/gboudreau/LEAF_Carwings_EasyAccess/issues/6#issue-328801574).

**Comment by FirePT** [comment]
Tried to create the setup to analyse network interactions of the app but couldn't. Does anyone have done it with a European account that can provide the new login config?

**Comment by gerfur1** [comment]
Yes, i had issues, but if i used the new base url in the old script it works. With the new baseurl in the new script it doesnt work.

Von meinem iPad gesendet

**Comment by gboudreau** [comment]
The new base URL you posted is working for me with the old script. It fails on the 1st request (`POST .../InitialApp.php`), with the same error as the old base URL that failed (`gworchest_160803A`):
```
[2018-06-05 06:43:29] [NissanConnect] Request: POST https://gdcportalgw.its-mo.com/gworchest_160803E/gdc/InitialApp.php {"custom_sessionid":"","initial_app_strings":"geORNtsZe5I4lRGjG9GZiA","RegionCode":"NCI","lg":"en-US","DCMID":"","VIN":"","tz":"Canada\/Eastern"}
Non-JSON response received for request to 'InitialApp.php'. Response received: "<!DOCTYPE HTML PUBLIC \"-\/\/IETF\/\/DTD HTML 2.0\/\/EN\">\n<html><head>\n<title>404 Not Found<\/title>\n<\/head><body>\n<h1>Not Found<\/h1>\n<p>The requested URL \/gworchest_160803E\/gdc\/InitialApp.php was not found on this server.<\/p>\n<\/body><\/html>\n"
```

Where did you get this new URL from?

The new version of the nissan-connect class is using the new API used by the official Nissan LEAF app (in Canada). It is completely different than the old API that was hosted on `gdcportalgw.its-mo.com`, so for sure, swapping the base URL to the old API won't work.

**Comment by ianshepherd** [comment]
Looks like you have a typo - I got mine working by changing the A to EC (not E) in the $baseURL (i.e. https://gdcportalgw.its-mo.com/gworchest_160803EC/gdc/ works)

**Comment by gboudreau** [comment]
Indeed, thanks. I changed the NissanConnect class back to its original state, with the new URL. That should resolve the issues for most/all users, for now.

**Comment by cyrillopez** [comment]
Thanks  @gerfur1 & @ianshepherd
