### ISSUE TITLE
API v2 changes

### ISSUE THREAD

**Issue by mjh53** [gboudreau/LEAF_Carwings_EasyAccess#8]
Nissan have updated the API and easy access doesn't work after this change.
Another project appears to have extracted the changes: https://gitlab.com/tobiaswkjeldsen/carwingsflutter/commit/76bd35f0bc888c54c2f001ee3d79b4e12e957754

I naively tried to implement these changes, but apparently not correctly : Request for 'UserLoginRequest.php' failed. Response received: {"status":404}

**Comment by jeremyakers** [comment]
I'm getting the same 404 when I try to make the same changes in my app. I tried to use mitmproxy with the app referenced in the gitlab link above but that app doesn't honor proxy server settings.

**Comment by gboudreau** [comment]
If you are in Europe, try [this file](https://raw.githubusercontent.com/gboudreau/nissan-connect-php/master/NissanConnect.class.php).
In US/Canada, use [this one](https://raw.githubusercontent.com/gboudreau/nissan-connect-php/new-api/NissanConnect.class.php).

**Comment by mjh53** [comment]
That works (for status and air conditioning) perfectly, thank you.
